"""Тестирование бизнес-логики приложения notes."""

from http import HTTPStatus

from pytils.translit import slugify

from notes.forms import WARNING
from notes.models import Note
from notes.tests.base import BaseTest


class TestLogic(BaseTest):
    """Класс для проверки бизнес-логики."""

    @classmethod
    def setUpTestData(cls):
        """Добавляем данные для отправки форм."""
        super().setUpTestData()
        cls.form_data = {
            'title': 'Новый заголовок',
            'text': 'Новый текст',
            'slug': 'new-slug'
        }

    def test_anonymous_user_cant_create_note(self):
        """Аноним не может создать заметку."""
        notes_count_before = Note.objects.count()
        self.client.post(self.add_url, data=self.form_data)
        self.assertEqual(Note.objects.count(), notes_count_before)

    def test_logged_user_can_create_note(self):
        """Авторизованный юзер может создать заметку."""
        Note.objects.all().delete()
        self.client.force_login(self.author)
        self.client.post(self.add_url, data=self.form_data)
        self.assertEqual(Note.objects.count(), 1)

        new_note = Note.objects.get()
        self.assertEqual(new_note.title, self.form_data['title'])
        self.assertEqual(new_note.text, self.form_data['text'])
        self.assertEqual(new_note.slug, self.form_data['slug'])
        self.assertEqual(new_note.author, self.author)

    def test_cant_create_duplicate_slug(self):
        """Невозможно создать две заметки с одинаковым slug."""
        notes_count_before = Note.objects.count()
        self.client.force_login(self.author)
        self.form_data['slug'] = self.note.slug
        response = self.client.post(self.add_url, data=self.form_data)
        self.assertFormError(
            response.context['form'],
            'slug',
            errors=(self.note.slug + WARNING)
        )
        self.assertEqual(Note.objects.count(), notes_count_before)

    def test_empty_slug_is_autogenerated(self):
        """При пустом slug он генерируется автоматически."""
        Note.objects.all().delete()
        self.client.force_login(self.author)
        self.form_data.pop('slug')
        self.client.post(self.add_url, data=self.form_data)
        self.assertEqual(Note.objects.count(), 1)

        new_note = Note.objects.get()
        expected_slug = slugify(self.form_data['title'])
        self.assertEqual(new_note.slug, expected_slug)

    def test_author_can_edit_note(self):
        """Автор может редактировать свою заметку."""
        notes_count_before = Note.objects.count()
        self.client.force_login(self.author)
        self.client.post(self.edit_url, data=self.form_data)

        self.note.refresh_from_db()
        self.assertEqual(self.note.title, self.form_data['title'])
        self.assertEqual(self.note.text, self.form_data['text'])
        self.assertEqual(self.note.slug, self.form_data['slug'])
        self.assertEqual(Note.objects.count(), notes_count_before)

    def test_other_user_cant_edit_note(self):
        """Пользователь не может редактировать чужую заметку."""
        notes_count_before = Note.objects.count()
        self.client.force_login(self.reader)

        original_title = self.note.title
        original_text = self.note.text
        original_slug = self.note.slug

        response = self.client.post(self.edit_url, data=self.form_data)
        self.assertEqual(response.status_code, HTTPStatus.NOT_FOUND)

        self.note.refresh_from_db()
        self.assertEqual(self.note.title, original_title)
        self.assertEqual(self.note.text, original_text)
        self.assertEqual(self.note.slug, original_slug)
        self.assertEqual(Note.objects.count(), notes_count_before)

    def test_author_can_delete_note(self):
        """Автор может удалить свою заметку."""
        notes_count_before = Note.objects.count()
        self.client.force_login(self.author)
        self.client.post(self.delete_url)
        self.assertEqual(Note.objects.count(), notes_count_before - 1)

    def test_other_user_cant_delete_note(self):
        """Пользователь не может удалить чужую заметку."""
        notes_count_before = Note.objects.count()
        self.client.force_login(self.reader)
        response = self.client.post(self.delete_url)
        self.assertEqual(response.status_code, HTTPStatus.NOT_FOUND)
        self.assertEqual(Note.objects.count(), notes_count_before)
